/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author akash
 */

import java.util.Scanner;

public class FrmDiceGame extends javax.swing.JFrame {
    Scanner keyedInput = new Scanner(System.in);
    
    //declaring final values for User Balance Amount, Computer Balance Amount and Round Limit
    final int USER_BAL_AMT_LMT = 20;
    final int COMP_BAL_AMT_LMT = 20;
    final int GAMES_PER_ROUND = 3;
    
    //declaring variables to store the user values including Balance and guess numbers
    int User_Bal_Amt = 0;
    int Comp_Bal_Amt = 0;
    int User_Bal_Diff = 0;
    int Bet_Amt = 0;
    int User_Guess_Num;
    int Comp_Roll_Num;
    
    //declaring variables to store the counter values for all checking and producing statistics
    int Round_Count = 0;
    int Round_Success_Count = 0;
    int Round_Missed_Count = 0;
    int Total_Rolls_Count = 0;
    int Total_Success_Count = 0;
    int Total_Miss_Count = 0;
    double Total_Success_Perc = 0;
    double Total_Miss_Perc = 0;
            
    public FrmDiceGame() {
        initComponents();
        
        //setting initial values to display in the Form for the 1st time
        User_Bal_Amt = USER_BAL_AMT_LMT;
        Comp_Bal_Amt = COMP_BAL_AMT_LMT;
        lblUserBalAmt.setText(String.format("$ "+User_Bal_Amt));
        lblCompBalAmt.setText(String.format("$ "+Comp_Bal_Amt));
        lblRoundTxt.setText("Round 1 of 3 :  ");
        btnContinue.setText("");
        btnPlaceNewBet.setText("Place New Bet");
        btnEndGame.setText("End Game");
        btnRestart.setText("RESTART");
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblGameRule1 = new javax.swing.JLabel();
        lblGameRule2 = new javax.swing.JLabel();
        lblGameRule3 = new javax.swing.JLabel();
        lblDummyLine1 = new javax.swing.JLabel();
        lblCompBalTxt = new javax.swing.JLabel();
        lblUserBalAmt = new javax.swing.JLabel();
        lblUserBalTxt = new javax.swing.JLabel();
        lblCompBalAmt = new javax.swing.JLabel();
        lblBetAmtTxt = new javax.swing.JLabel();
        txtBetAmt = new javax.swing.JTextField();
        lblCompRollTxt = new javax.swing.JLabel();
        lblRoundTxt = new javax.swing.JLabel();
        txtUserGuessNum = new javax.swing.JTextField();
        lblUserGuessTxt1 = new javax.swing.JLabel();
        btnRollDice = new javax.swing.JButton();
        lblRoundResultTxt = new javax.swing.JLabel();
        btnPlaceNewBet = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        btnEndGame = new javax.swing.JButton();
        lblDummyLine2 = new javax.swing.JLabel();
        lblStatsTitle = new javax.swing.JLabel();
        lblTotalRollsTxt = new javax.swing.JLabel();
        lblTotalRollsCount = new javax.swing.JLabel();
        lblTotalSuccessTxt = new javax.swing.JLabel();
        lblTotalSuccessCount = new javax.swing.JLabel();
        lblTotalMissTxt = new javax.swing.JLabel();
        lblTotalMissCount = new javax.swing.JLabel();
        lblTotalSuccessPerc = new javax.swing.JLabel();
        lblTotalMissPerc = new javax.swing.JLabel();
        lblWinLossDesc = new javax.swing.JLabel();
        lblCompRollNum = new javax.swing.JLabel();
        btnRestart = new javax.swing.JButton();
        lblBetErrorMsg = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("The Castle Of Chance");

        lblGameRule1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblGameRule1.setForeground(new java.awt.Color(0, 153, 255));
        lblGameRule1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGameRule1.setText("Game Rule 1 :  Each betting game involves 3 rounds. Your bet should be a whole number and not exceed your Balance amount.");

        lblGameRule2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblGameRule2.setForeground(new java.awt.Color(0, 153, 255));
        lblGameRule2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGameRule2.setText("Game Rule 2 :  Your GUESS on the dice roll should be between 1 and 6.");

        lblGameRule3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblGameRule3.setForeground(new java.awt.Color(0, 153, 255));
        lblGameRule3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGameRule3.setText("Game Rule 3 :  You WIN the challenge, if you win 2 or more rounds.");

        lblDummyLine1.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        lblCompBalTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCompBalTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompBalTxt.setText("Computer Balance");

        lblUserBalAmt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserBalAmt.setForeground(new java.awt.Color(255, 0, 0));
        lblUserBalAmt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserBalAmt.setText(" 0");

        lblUserBalTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserBalTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserBalTxt.setText("Your Balance");

        lblCompBalAmt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCompBalAmt.setForeground(new java.awt.Color(255, 0, 0));
        lblCompBalAmt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompBalAmt.setText(" 0");

        lblBetAmtTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBetAmtTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBetAmtTxt.setText("BET Amount");

        txtBetAmt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBetAmt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBetAmt.setText("0");
        txtBetAmt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBetAmtFocusLost(evt);
            }
        });

        lblCompRollTxt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblCompRollTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompRollTxt.setText("Computer Rolled");

        lblRoundTxt.setText("         ");

        txtUserGuessNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUserGuessNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserGuessNum.setText("0");
        txtUserGuessNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserGuessNumFocusLost(evt);
            }
        });

        lblUserGuessTxt1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblUserGuessTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserGuessTxt1.setText("Your Guess");

        btnRollDice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRollDice.setForeground(new java.awt.Color(204, 0, 51));
        btnRollDice.setText("Roll the Dice");
        btnRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollDiceActionPerformed(evt);
            }
        });

        lblRoundResultTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblRoundResultTxt.setForeground(new java.awt.Color(102, 0, 255));
        lblRoundResultTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoundResultTxt.setText("    ");

        btnPlaceNewBet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlaceNewBet.setText(" ");
        btnPlaceNewBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceNewBetActionPerformed(evt);
            }
        });

        btnContinue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnContinue.setText("  ");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        btnEndGame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEndGame.setText(" ");
        btnEndGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndGameActionPerformed(evt);
            }
        });

        lblDummyLine2.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        lblStatsTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblStatsTitle.setForeground(new java.awt.Color(0, 51, 255));
        lblStatsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatsTitle.setText(" ");

        lblTotalRollsTxt.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTotalRollsTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalRollsTxt.setText(" ");

        lblTotalRollsCount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalRollsCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalRollsCount.setText(" ");

        lblTotalSuccessTxt.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTotalSuccessTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalSuccessTxt.setText(" ");

        lblTotalSuccessCount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalSuccessCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalSuccessCount.setText(" ");

        lblTotalMissTxt.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTotalMissTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalMissTxt.setText(" ");

        lblTotalMissCount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalMissCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalMissCount.setText(" ");

        lblTotalSuccessPerc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalSuccessPerc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalSuccessPerc.setText(" ");

        lblTotalMissPerc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalMissPerc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalMissPerc.setText(" ");

        lblWinLossDesc.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblWinLossDesc.setForeground(new java.awt.Color(0, 102, 255));
        lblWinLossDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWinLossDesc.setText("                  ");

        lblCompRollNum.setText("    ");

        btnRestart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRestart.setText("  ");
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        lblBetErrorMsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBetErrorMsg.setForeground(new java.awt.Color(255, 0, 51));
        lblBetErrorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBetErrorMsg.setText(" ");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/The Castle of Change-Logo.png"))); // NOI18N
        lblLogo.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lblUserBalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCompBalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalMissTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTotalSuccessTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                                .addComponent(lblTotalRollsTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTotalSuccessCount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotalMissCount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTotalMissPerc, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(lblTotalSuccessPerc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblTotalRollsCount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(txtBetAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDummyLine2)
                            .addComponent(lblDummyLine1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBetAmtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRollDice))
                        .addGap(84, 84, 84)
                        .addComponent(lblCompRollNum, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(txtUserGuessNum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(lblStatsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblUserBalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRoundTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblUserGuessTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(397, 397, 397)
                                    .addComponent(lblCompBalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblBetErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRoundResultTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblWinLossDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnPlaceNewBet, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEndGame, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGameRule3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGameRule2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCompRollTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRestart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(175, 175, 175))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblGameRule1)
                            .addGap(54, 54, 54)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(32, 32, 32)
                .addComponent(lblGameRule1)
                .addGap(18, 18, 18)
                .addComponent(lblGameRule2)
                .addGap(18, 18, 18)
                .addComponent(lblGameRule3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDummyLine1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompBalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserBalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserBalAmt)
                    .addComponent(lblCompBalAmt))
                .addGap(18, 18, 18)
                .addComponent(lblBetAmtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBetAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblBetErrorMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserGuessTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoundTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompRollTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserGuessNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRollDice)
                    .addComponent(lblCompRollNum))
                .addGap(26, 26, 26)
                .addComponent(lblRoundResultTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContinue)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlaceNewBet)
                    .addComponent(btnEndGame)
                    .addComponent(btnRestart))
                .addGap(18, 18, 18)
                .addComponent(lblDummyLine2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatsTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalRollsTxt)
                    .addComponent(lblTotalRollsCount))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalSuccessTxt)
                    .addComponent(lblTotalSuccessCount)
                    .addComponent(lblTotalSuccessPerc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalMissTxt)
                    .addComponent(lblTotalMissCount)
                    .addComponent(lblTotalMissPerc))
                .addGap(90, 90, 90)
                .addComponent(lblWinLossDesc)
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here: 

        //logic that gets triggered, when CONTINUE button is clicked
        //setting up the label text messages, depending on the round count 
        if (Round_Count < GAMES_PER_ROUND)
        {
            if (Round_Count == 1)
            {
                lblRoundTxt.setText("Round 2 of 3 :  ");
            }
            else if (Round_Count == 2)
            {
                lblRoundTxt.setText("Round 3 of 3 :  ");
            }
            lblCompRollNum.setText("");
            txtUserGuessNum.setText("0");
            lblRoundResultTxt.setText("");
        }
        else
        {
            //Adjusting the User Balance amount and Computer Balance amount, depending on the user winning or losing the game 
           if (Round_Success_Count >= 2)
           {
               lblRoundResultTxt.setText("Success BETTING. You have Won $ "+Bet_Amt);
               User_Bal_Amt = User_Bal_Amt + Bet_Amt;
               Comp_Bal_Amt = Comp_Bal_Amt - Bet_Amt;
           }
           else
           {
               lblRoundResultTxt.setText("Failure BETTING. You have Lost $ "+Bet_Amt);
               User_Bal_Amt = User_Bal_Amt - Bet_Amt;
               Comp_Bal_Amt = Comp_Bal_Amt + Bet_Amt;
           }
           lblUserBalAmt.setText(String.format("$ "+User_Bal_Amt));
           lblCompBalAmt.setText(String.format("$ "+ Comp_Bal_Amt));
           btnContinue.setText("");
           btnPlaceNewBet.setText("Place New Bet");
           btnEndGame.setText("End Game");
           btnRestart.setText("RESTART");
        }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnPlaceNewBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceNewBetActionPerformed
        // TODO add your handling code here:
        //logic that gets triggered, when PLACE NEW BET button is clicked
        //Resetting all the round counts, statistics and all text/label fields, to start a new betting game
        Round_Count = 0;
        Round_Success_Count = 0;
        Round_Missed_Count = 0;
        lblRoundTxt.setText("Round 1 of 3 :  ");
        txtBetAmt.setText("0");
        lblCompRollNum.setText("");
        txtUserGuessNum.setText("0");
        lblRoundResultTxt.setText("");
        btnContinue.setText("");
        lblBetErrorMsg.setText("");
        
        lblStatsTitle.setText("");
        lblTotalRollsTxt.setText("");
        lblTotalSuccessTxt.setText("");
        lblTotalMissTxt.setText("");
        lblTotalRollsCount.setText("");
        lblTotalSuccessCount.setText("");
        lblTotalMissCount.setText("");
        lblTotalSuccessPerc.setText("");
        lblTotalMissPerc.setText("");
        lblWinLossDesc.setText("");
    }//GEN-LAST:event_btnPlaceNewBetActionPerformed

    private void btnRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollDiceActionPerformed
        // TODO add your handling code here:
        //logic that gets triggered, when ROLL DICE button is clicked
        //Generates the random number between 1 and 6, when user clicks Roll Dice. 
        //If User Guess is same as Computer generated number, it is a Correct Guess. Else, Missed count will be incremented.
        if (User_Guess_Num > 0)
        {
            btnContinue.setText("CONTINUE");
            btnPlaceNewBet.setText("");
            btnEndGame.setText("");
            btnRestart.setText("");
            User_Guess_Num = Integer.parseInt(txtUserGuessNum.getText());
            Comp_Roll_Num = (int)Math.round(Math.random()*5+1);
            lblCompRollNum.setText(String.format(""+Comp_Roll_Num));
            Round_Count = Round_Count + 1;
            Total_Rolls_Count = Total_Rolls_Count + 1;
        
            if (User_Guess_Num == Comp_Roll_Num)
            {
                Round_Success_Count = Round_Success_Count + 1;
                Total_Success_Count = Total_Success_Count + 1;
                lblRoundResultTxt.setText("Good Guess. You WON. Keep Going");
            }
            else
            {
                Round_Missed_Count = Round_Missed_Count + 1;
                Total_Miss_Count = Total_Miss_Count + 1;
                lblRoundResultTxt.setText("Wrong Guess. You LOST. Try again");
            }    
            if (Round_Count == 3)
            {
                btnContinue.setText("RESULT");
            }
        }
 
    }//GEN-LAST:event_btnRollDiceActionPerformed

    private void btnEndGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndGameActionPerformed
        // TODO add your handling code here:
        //logic that gets triggered, when END GAME button is clicked
        //Generates the statistics, to include Total number of dice rolled, total correct guess, total incorrect guess and percentage calculated limiting to 2 decimals. 
        lblStatsTitle.setText("GAME STATISTICS");
        lblTotalRollsTxt.setText("Total Number of Rolls                                     :  ");
        lblTotalSuccessTxt.setText("Number of CORRECT Guess you made       :  ");
        lblTotalMissTxt.setText("Number of INCORRECT Guess you made  :  ");
        lblTotalRollsCount.setText(String.valueOf(Total_Rolls_Count));
        lblTotalSuccessCount.setText(String.valueOf(Total_Success_Count));
        lblTotalMissCount.setText(String.valueOf(Total_Miss_Count));
        if (Total_Rolls_Count > 0)
        {
           Total_Success_Perc = ((double)Total_Success_Count / (double)Total_Rolls_Count)*100;
           lblTotalSuccessPerc.setText(String.format("%.2f",Total_Success_Perc)+" %");
           Total_Miss_Perc = ((double)Total_Miss_Count / (double)Total_Rolls_Count)*100;
           lblTotalMissPerc.setText(String.format("%.2f",Total_Miss_Perc)+" %");
        }
        else
        {
           Total_Success_Perc = 0;
           lblTotalSuccessPerc.setText(String.format("%.2f",Total_Success_Perc)+" %");
           Total_Miss_Perc = 0;
           lblTotalMissPerc.setText(String.format("%.2f",Total_Miss_Perc)+" %");
        }
        
        //Display final message depending on the Loss or Gain 
        if (User_Bal_Amt == USER_BAL_AMT_LMT)
        {
           lblWinLossDesc.setText("No Loss - No Gain. Your Current Balance is $ " + User_Bal_Amt);
        }
        else if (User_Bal_Amt > USER_BAL_AMT_LMT)
        {
            User_Bal_Diff = User_Bal_Amt - USER_BAL_AMT_LMT;
            lblWinLossDesc.setText("Congrats. You made a profit of $ " + User_Bal_Diff + ".   Your Current Balance is $ " + User_Bal_Amt);
        }
        else
        {
            User_Bal_Diff = USER_BAL_AMT_LMT - User_Bal_Amt;
            lblWinLossDesc.setText("Sorry. You made a loss of $ " + User_Bal_Diff + ".   Your Current Balance is $ " + User_Bal_Amt);
        }
    }//GEN-LAST:event_btnEndGameActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        // TODO add your handling code here:
        //logic that gets triggered, when RESTART button is clicked
        //Re-Initializing all the Labels, texts, Balance Amounts, Round Counts to "0" or spaces
        lblStatsTitle.setText("");
        lblTotalRollsTxt.setText("");
        lblTotalSuccessTxt.setText("");
        lblTotalMissTxt.setText("");
        lblTotalRollsCount.setText("");
        lblTotalSuccessCount.setText("");
        lblTotalMissCount.setText("");
        lblTotalSuccessPerc.setText("");
        lblTotalMissPerc.setText("");
        
        User_Bal_Amt = USER_BAL_AMT_LMT;
        Comp_Bal_Amt = COMP_BAL_AMT_LMT;
        lblUserBalAmt.setText(String.format("$ "+User_Bal_Amt));
        lblCompBalAmt.setText(String.format("$ "+Comp_Bal_Amt));
        lblRoundTxt.setText("Round 1 of 3 :  ");
        btnContinue.setText("");
        btnPlaceNewBet.setText("Place New Bet");
        btnEndGame.setText("End Game");
        btnRestart.setText("RESTART");
        
        Round_Count =0;
        Round_Success_Count = 0;
        Round_Missed_Count = 0;
        txtBetAmt.setText("0");
        lblCompRollNum.setText("");
        txtUserGuessNum.setText("0");
        lblRoundResultTxt.setText("");
        btnContinue.setText("");
        lblBetErrorMsg.setText("");
        lblWinLossDesc.setText("");
        
        Total_Rolls_Count = 0;
        Total_Success_Count = 0;
        Total_Miss_Count = 0;
        Total_Success_Perc = 0;
        Total_Miss_Perc = 0;
    }//GEN-LAST:event_btnRestartActionPerformed

    private void txtBetAmtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBetAmtFocusLost
        // TODO add your handling code here:
        //logic that gets triggered, when user inputs Bet Amount and comes out of the text field
        //Logic to check whether Bet Amount is more than Balance amount or Bet amount is negative. If YES, will display error message and discard the input
        if (Round_Count == 0)
        {
             Bet_Amt = Integer.parseInt(txtBetAmt.getText());
             if (Bet_Amt > User_Bal_Amt)
             {
                 lblBetErrorMsg.setText("ERROR. Your BET Amount cannot exceed your Balance Amount");
                 txtBetAmt.setText("0");
                 Bet_Amt = 0;
             }
             else if (Bet_Amt < 0)
                 {
                 lblBetErrorMsg.setText("ERROR. Bad input on the Bet Amount");
                 txtBetAmt.setText("0");
                 Bet_Amt = 0; 
                 }
             else
             {        
                 lblBetErrorMsg.setText("");
             }
        }
        else
        {
             lblBetErrorMsg.setText("ERROR. You cannot change the Bet in the middle of the Round.");
             txtBetAmt.setText(String.valueOf(Bet_Amt));
        }
    }//GEN-LAST:event_txtBetAmtFocusLost

    private void txtUserGuessNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserGuessNumFocusLost
        // TODO add your handling code here:
        //logic that gets triggered, when user inputs Guess Number and comes out of the text field
        //Logic to check whether Guess Number is between 1 and 6. If NOT, will display error message and discard the input
        lblBetErrorMsg.setText("");
        User_Guess_Num = Integer.parseInt(txtUserGuessNum.getText());
        if ((User_Guess_Num <= 0) || (User_Guess_Num > 6))
        {
            txtUserGuessNum.setText("0");
            User_Guess_Num = 0;
            lblRoundResultTxt.setText("ERROR USER INPUT. You need to choose between 1 and 6");
        }
        else
        {
            lblRoundResultTxt.setText("");
        }
    }//GEN-LAST:event_txtUserGuessNumFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDiceGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnEndGame;
    private javax.swing.JButton btnPlaceNewBet;
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnRollDice;
    private javax.swing.JLabel lblBetAmtTxt;
    private javax.swing.JLabel lblBetErrorMsg;
    private javax.swing.JLabel lblCompBalAmt;
    private javax.swing.JLabel lblCompBalTxt;
    private javax.swing.JLabel lblCompRollNum;
    private javax.swing.JLabel lblCompRollTxt;
    private javax.swing.JLabel lblDummyLine1;
    private javax.swing.JLabel lblDummyLine2;
    private javax.swing.JLabel lblGameRule1;
    private javax.swing.JLabel lblGameRule2;
    private javax.swing.JLabel lblGameRule3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRoundResultTxt;
    private javax.swing.JLabel lblRoundTxt;
    private javax.swing.JLabel lblStatsTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalMissCount;
    private javax.swing.JLabel lblTotalMissPerc;
    private javax.swing.JLabel lblTotalMissTxt;
    private javax.swing.JLabel lblTotalRollsCount;
    private javax.swing.JLabel lblTotalRollsTxt;
    private javax.swing.JLabel lblTotalSuccessCount;
    private javax.swing.JLabel lblTotalSuccessPerc;
    private javax.swing.JLabel lblTotalSuccessTxt;
    private javax.swing.JLabel lblUserBalAmt;
    private javax.swing.JLabel lblUserBalTxt;
    private javax.swing.JLabel lblUserGuessTxt1;
    private javax.swing.JLabel lblWinLossDesc;
    private javax.swing.JTextField txtBetAmt;
    private javax.swing.JTextField txtUserGuessNum;
    // End of variables declaration//GEN-END:variables
}
